app = "matchboxd"
primary_region = "dfw"

[build]

[env]
  NODE_ENV = "production"
  REQUEST_LIMIT = "100"  # Max requests per month

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
[http_service.concurrency]
  type = "requests"
  hard_limit = 10
  soft_limit = 5

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"